agent:
  memory_capacity: 1000
  memory_retention_seconds: 3600
  mode: single
ai_providers:
  deepseek:
    api_key: sk-c93bf20a43554ead910a9e148131b04a
    available_models:
    - deepseek-coder
    - deepseek-chat
    default_model: deepseek-coder
  google:
    api_key: ''
    available_models:
    - gemini-pro
    - gemini-ultra
    default_model: gemini-pro
  openai:
    api_key: ''
    available_models:
    - gpt-4o
    - gpt-4-turbo
    - gpt-3.5-turbo
    default_model: gpt-4o
api:
  anthropic_api_key: ${ANTHROPIC_API_KEY}
  openai_api_key: ${OPENAI_API_KEY}
logging:
  file: anus.log
  level: info
model:
  model_name: gpt-4
  provider: openai
tools:
- web_browser
- search
- file_processor
- code_executor
- image_analyzer
ui:
  theme: dark
